config/routes.rb
Rails.application.routes.draw do
  resources :surveys, :path => 'ankieta', path_names: { new: 'nowa' }, :except => [:edit, :update] do
    member do
		get 'stats', :path => 'wyniki'
	end
  end
  devise_for :administrators, :path => 'uzytkownik', path_names: { sign_in: 'logowanie', sign_out: 'wylogowywanie', edit: 'profil' }
  get 'static_pages/help'
  post 'fill_survey' => 'surveys#fill', controller: 'surveys'
  root 'surveys#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_one :category, class_name:Category, foreign_key: :id
  has_many :questions, class_name:Question, dependent: :destroy
  has_many :answers, class_name:Answer, dependent: :destroy, through: :questions
  belongs_to :administrator, class_name: Administrator, foreign_key: :id, optional: true
  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :category_id, presence: true
  validates_associated :questions
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy, :stats, :is_survey_creator?, :is_opened?, :is_available?]
	before_action :already_filled_this_survey?, only: [:show]
	before_action :is_survey_author?, only: [:show]
	before_action :is_opened?, only: [:show]
	before_action :is_logged?, only: [:new]
	before_action :is_available?, only: [:stats]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    @respondent = Respondent.new
  end
  
  def fill
	Survey.transaction do
		respondent_param = params[:respondent]
		if(respondent_param.nil?)
			@respondent = Respondent.create(:age => nil, :sex => nil, :education => nil, :location => nil, :ip_address => request.remote_ip)
		else
			@respondent = Respondent.create(:age => respondent_param[:age], :sex => respondent_param[:sex], :education => respondent_param[:education], :location => respondent_param[:location], :ip_address => request.remote_ip)
		end
		question_param = params[:question]
		question_param.each do |question, answers|
			answers.each do |answer_id|
				answer_respondent = AnswerRespondent.create(:answer_id => answer_id, :respondent_id => @respondent.id)
				if !answer_respondent.valid?
					raise ActiveRecord::Rollback
				end
			end
		end
		respond_to do |format|
		  if @respondent.save
			format.html { redirect_to root_path }
			format.json { redirect_to root_path, notice: 'Dziękujemy za wypełnienie ankiety!' }
			flash[:success] = 'Dziękujemy za wypełnienie ankiety!'
		  else
		    raise ActiveRecord::Rollback
			format.html { redirect_to root_path }
			format.json { redirect_to root_path, notice: 'Wystąpił błąd przy wypełnianiu ankiety!' }
			flash[:danger] = 'Wystąpił błąd przy wypełnianiu ankiety!'
		  end
		end
	end
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

   # POST /surveys
  # POST /surveys.json
  def create
  
	Survey.transaction do
			@survey = Survey.new(survey_params)
			@survey.administrator_id = current_administrator.id
			@questions = []
			@answers = []
			question_param = params[:questions]
			answer_param = params[:answers]
			question_type_param = params[:question_type]
			
			question_param.each.with_index do |content, index_q|
				indeks = index_q.to_s
				if question_type_param.nil?
					question = Question.new(:content => content, :order => index_q, :question_type => "JEDNOKROTNEGO_WYBORU")
				else
					if question_type_param.include?(indeks)
						question = Question.new(:content => content, :order => index_q, :question_type => "WIELOKROTNEGO_WYBORU")
					else
						question = Question.new(:content => content, :order => index_q, :question_type => "JEDNOKROTNEGO_WYBORU")
					end
				end
				if !question.save 
					raise ActiveRecord::Rollback
				end
				replies = answer_param[indeks]
					replies.each.with_index do |reply, index_a|
						answer = Answer.new(:reply => reply, :order => index_a, :question_id => question.id)
						if !answer.save
							raise ActiveRecord::Rollback
						end
					end
				@questions.push(question)
			end
			@survey.questions = @questions
		respond_to do |format|
		  if @survey.save
			format.html { redirect_to root_path }
			format.json { redirect_to root_path }
			flash[:success] = 'Poprawnie utworzono ankietę.'
		  else
			raise ActiveRecord::Rollback
			format.html { render :new }
			format.json { render json: @survey.errors.full_messages, status: :unprocessable_entity}
		  end
		end
	end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url }
      format.json { head :no_content }
			flash[:success] = 'Poprawnie usunięto ankietę.'
    end
  end

  def stats
	
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
		def already_filled_this_survey?
			answer_respondents = AnswerRespondent.where(answer_id:@survey.questions.first.answers).each do |ar|
				if Respondent.exists?(ar.respondent_id)
					if Respondent.find(ar.respondent_id).ip_address == request.remote_ip
						flash[:danger] = "Każdy użytkownik może wypełnić ankietę TYLKO RAZ."
						#redirect_to root_path   ##odkomentować jeśli chce się zablokować ponowny dostęp do ankiety po jej wypełnieniu
					end
				end
			end
		end

		def is_logged?
			if current_administrator == nil
				flash[:danger] = "Musisz być zalogowany, żeby mieć dostęp do tej podstrony."
				redirect_to root_path
			end
		end

		def is_survey_author?
			if (current_administrator != nil && current_administrator.id == @survey.administrator_id)
					@is_survey_author = true
			else
					@is_survey_author = false
			end
		end
		
		def is_opened?
			if (Time.now <=> @survey.start_date) == -1 || (Time.now <=> @survey.end_date) == 1
				flash[:danger] = "Ankieta nie jest w tej chwili dostępna."
				redirect_to root_path
			end
		end

		def is_available?
			if @survey.is_available_for_all || (current_administrator != nil && current_administrator.id == @survey.administrator_id)
				return
			else
				respondent_has_access = false
				if @survey.is_public
					answer_respondents = AnswerRespondent.where(answer_id:@survey.questions.first.answers).each do |ar|
						if Respondent.exists?(ar.respondent_id)
							if Respondent.find(ar.respondent_id).ip_address == request.remote_ip
								respondent_has_access = true
							end
						end
					end
				end
				if !respondent_has_access
					flash[:danger] = "Nie masz dostępu do wyników ankiety"
					redirect_to root_path
				end
			end
		end

    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:name, :start_date, :end_date, :is_opened, :is_public, :is_available_for_all, :administrator_id, :category_id, :is_age_required, :is_sex_required, :is_education_required, :is_location_required)
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_answer.erb
<div class="input-group answer-generator">
    <span class="input-group-addon hidden"></span>
    <%= text_field_tag nil, nil, id: nil, placeholder: 'Naciśnij, jeśli chcesz dodać odpowiedź', class: "form-control pressForNewAnswer" %>
    <span class="input-group-btn hidden">
        <button class="btn btn-default remove-answer" type="button" data-toggle="tooltip" data-placement="right" title="Naciśnij, aby usunąć odpowiedź">X</button>
    </span>
</div>

app/views/surveys/_form.html.erb
<%= form_for(survey) do |f| %>
  <% if survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.text_field :start_date %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.text_field :end_date %>
  </div>

  <div class="field">
    <%= f.label :is_opened %>
    <%= f.check_box :is_opened %>
  </div>

  <div class="field">
    <%= f.label :is_public %>
    <%= f.check_box :is_public %>
  </div>

  <div class="field">
    <%= f.label :is_available_for_all %>
    <%= f.check_box :is_available_for_all %>
  </div>

  <div class="field">
    <%= f.label :administrator_id %>
    <%= f.number_field :administrator_id %>
  </div>

  <div class="field">
    <%= f.label :category_id %>
    <%= f.number_field :category_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/_question.erb
<div>
     <div class="question">
        <div class="input-group input-group-lg">
            <span class="input-group-addon"><strong>1.</strong></span>
                <%= text_field_tag "questions[]", nil, id: nil, placeholder: 'Pytanie', class: "form-control" %>
            <span class="input-group-btn">
            <button class="btn btn-default remove-question" type="button" data-toggle="tooltip" data-placement="right" title="Naciśnij, aby usunąć pytanie">X</button>
        </span>
     </div>
     <div class="checkbox multiplechoice">
        <label><input name="question_type[]" type="checkbox" value="0" />pytanie wielokrotnego wyboru</label>
     </div>
     </div>
     <div class="answers">
        <div class="input-group answer-generator">
            <span class="input-group-addon">1.</span>
            <%= text_field_tag "answers[0][]", nil, id: nil, placeholder: 'Odpowiedź', class: "form-control" %>
            <span class="input-group-btn">
                <button class="btn btn-default remove-answer" type="button" data-toggle="tooltip" data-placement="right" title="Naciśnij, aby usunąć odpowiedź">X</button>
            </span>
        </div>
        <div class="input-group answer-generator">
            <span class="input-group-addon">2.</span>
            <%= text_field_tag "answers[0][]", nil, id: nil, placeholder: 'Odpowiedź', class: "form-control" %>
            <span class="input-group-btn">
                <button class="btn btn-default remove-answer" type="button" data-toggle="tooltip" data-placement="right" title="Naciśnij, aby usunąć odpowiedź">X</button>
            </span>
        </div>
        <%= render "answer" %>
     </div>
</div>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<% provide(:title, "Ankiety") %>
<h1>Ankiety</h1>

<% if administrator_signed_in? %>
<h2>Twoje ankiety</h2>
<div style="overflow-x:auto;">
	<table class="table">
	  <thead>
		<tr>
		  <th>Nazwa</th>
		  <th>Data rozpoczęcia</th>
		  <th>Data zakończenia</th>
			<th>Dostęp do wyników</th>
		  <th>Kategoria</th>
		  <th colspan="3"></th>
		</tr>
	  </thead>

	  <tbody>
			<% @surveys.where(:administrator_id => current_administrator.id).each do |survey| %>
			  <tr>
				<td><%= survey.name %></td>
				<td><%= survey.start_date.strftime('%d-%m-%Y') %></td>
				<td><%= survey.end_date.strftime('%d-%m-%Y') %></td>
				<% if(survey.is_available_for_all) %>
					<td><%= link_to 'dla WSZYSTKICH', stats_survey_path(survey.id) %></td>
				<% elsif(survey.is_public) %>
					<td><%= link_to 'tylko dla ANKIETOWANYCH', stats_survey_path(survey.id) %></td>
				<% else %>
					<td><%= link_to 'tylko dla AUTORA', stats_survey_path(survey.id) %></td>
				<% end %>
				<td><%= Category.find(survey.category_id).name %></td>
				<td><%= link_to 'Przeglądnij', survey, action: :show %></td>
				<td><%= link_to 'Usuń', survey, method: :delete, data: { confirm: 'Czy jesteś pewien?' } %></td>
			  </tr>
			<% end %>
		</tbody>
	</table>
</div>
		<%= link_to 'Utwórz nową ankietę', new_survey_path %>
<% end %>
<br>
<h2>Ostatnio dodane</h2>
<div style="overflow-x:auto;">
	<table class="table">
	  <thead>
		<tr>
		  <th>Nazwa</th>
		  <th>Data rozpoczęcia</th>
		  <th>Data zakończenia</th>
			<th>Dostęp do wyników</th>
  		<th>Administrator</th>
		  <th>Kategoria</th>
		  <th colspan="3"></th>
		</tr>
	  </thead>

	  <tbody>
			<% @surveys.last(5).reverse.each do |survey| %>
			  <tr>
				<td><%= survey.name %></td>
				<td><%= survey.start_date.strftime('%d-%m-%Y') %></td>
				<td><%= survey.end_date.strftime('%d-%m-%Y') %></td>
				<% if(survey.is_available_for_all) %>
					<td><%= link_to 'dla WSZYSTKICH', stats_survey_path(survey.id) %></td>
				<% elsif(survey.is_public) %>
					<td><%= link_to 'tylko dla ANKIETOWANYCH', stats_survey_path(survey.id) %></td>
				<% else %>
					<td>tylko dla AUTORA</td>
				<% end %>
				<td><%= Administrator.find(survey.administrator_id).login %></td>
				<td><%= Category.find(survey.category_id).name %></td>
				<td><%= link_to 'Wypełnij', survey, action: :show %></td>
			  </tr>
			<% end %>
	  </tbody>
	</table>
</div>

<br>
<h2>Wszystkie ankiety</h2>
<% categories = Category.all.order(:name) %>
<div class="panel panel-default">
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
		<% categories.each do |c| %>
			<% if(c == categories.first()) %>
    		<li role="presentation" class="active"><a href="#<%= c.name %>" aria-controls="<%= c.name %>" role="tab" data-toggle="tab"><%= c.name %></a></li>
			<% else %>
    		<li role="presentation"><a href="#<%= c.name %>" aria-controls="<%= c.name %>" role="tab" data-toggle="tab"><%= c.name %></a></li>
			<% end %>
		<% end %>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
		<% categories.each do |c| %>
				<% if(c == categories.first()) %>
					<div role="tabpanel" class="tab-pane fade in active" id="<%= c.name %>">
				<% else %>
					<div role="tabpanel" class="tab-pane fade" id="<%= c.name %>">
				<% end %>
					<% if @surveys.where(category_id: c.id).present? %>
						<div style="overflow-x:auto;">
							<table class="table">
								<thead>
									<tr>
										<th>Nazwa</th>
										<th>Data rozpoczęcia</th>
										<th>Data zakończenia</th>
										<th>Dostęp do wyników</th>
										<th>Administrator</th>	
										<th>Kategoria</th>
										<th colspan="3"></th>
									</tr>
								</thead>

								<tbody>
									<% @surveys.where(category_id: c.id).each do |survey| %>
										<tr>
										<td><%= survey.name %></td>
										<td><%= survey.start_date.strftime('%d-%m-%Y') %></td>
										<td><%= survey.end_date.strftime('%d-%m-%Y') %></td>
										<% if(survey.is_available_for_all) %>
											<td><%= link_to 'dla WSZYSTKICH', stats_survey_path(survey.id) %></td>
										<% elsif(survey.is_public) %>
											<td><%= link_to 'tylko dla ANKIETOWANYCH', stats_survey_path(survey.id) %></td>
										<% else %>
											<td>tylko dla AUTORA</td>
										<% end %>
										<td><%= Administrator.find(survey.administrator_id).login %></td>
										<td><%= Category.find(survey.category_id).name %></td>
										<td><%= link_to 'Wypełnij', survey, action: :show %></td>
										</tr>
									<% end %>
								</tbody>
							</table>
						</div>
						<% else %>
							<h3>Brak ankiet</h3>
						<% end %>		
					</div>
		<% end %>
  </div>

</div>

app/views/surveys/new.html.erb
<% provide(:title, "Kreator ankiety") %>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-offset-1 col-lg-10 col-lg-offset-1">
    <%= form_for(@survey, format: :json, html: {:id => 'survey-generator-form',:class => 'panel panel-default'} ) do |f| %>

        <div id="survey-generator">
            <div id="survey-name" class="input-group input-group-lg">
                <h2>Nazwa ankiety</h2>
                <div class="col-lg-offset-1 col-lg-10 col-lg-offset-1">
                    <%= f.text_field :name, class: "form-control", placeholder: 'Nazwa ankiety' %>
                </div>
            </div>
            <div class="start-date">
                <h3>Data rozpoczęcia</h3>
                <%= f.text_field :start_date, class: "form-control", placeholder: 'Data rozpoczęcia' %>
            </div>
            <div class="end-date">
                <h3>Data zakończenia</h3>
                <%= f.text_field :end_date, class: "form-control", placeholder: 'Data zakończenia' %>
            </div>
            <div class="category-dropdown">
                <h3>Kategoria:</h3>
                <div class="form-group">
                    <%= f.collection_select(:category_id, Category.order('name'), :id, :name, {}, {:class=>"form-control category"}) %>
                </div>
            </div>
            <div class="survey-checkboxes">
                <h3>Ankietowani mają być pytani o:</h3>                
                <div class="checkbox">
                    <label>
                        <%= f.check_box :is_age_required %> wiek
                    </label>
                </div>
                <div class="checkbox">
                    <label>
                        <%= f.check_box :is_sex_required %> płeć
                    </label>
                </div>
                <div class="checkbox">
                    <label>
                        <%= f.check_box :is_education_required %> wykształcenie
                    </label>
                </div>
                <div class="checkbox">
                    <label>
                        <%= f.check_box :is_location_required %> zamieszkanie
                    </label>
                </div>
            </div>
            <div class="survey-checkboxes">
                <h3>Wyniki będą dostępne dla:</h3>
                <div class="checkbox">
                    <label>
                        <%= f.check_box :is_public %> ankietowanych
                    </label>
                </div>
                <div class="checkbox">
                    <label>
                        <%= f.check_box :is_available_for_all %> wszystkich
                    </label>
                </div>
            </div>
            <%= render 'question' %>
        </div>
        <div>
            <div id="new-question">
                <a href="javascript:;" id="add_new_question" class="btn btn-default">Nowe Pytanie</a>
            </div>
            <div>
                <%= f.submit "Zapisz ankietę", class: "btn btn-primary btn-lg"%>
            </div>
        </div>
        <% end %>

            <div style="display: none;" id="new_question">
                <%= render 'question' %>
            </div>
            <div style="display: none;" id="new_answer">
                <%= render 'answer' %>
            </div>
</div>

app/views/surveys/show.html.erb
<% if(@is_survey_author) %>
	<div class="alert alert-info" role="alert">
	  <button type="button" class="close">&times;</button>
	  Jako autor ankiety nie możesz wziąć w niej udziału
	</div>
  <% end %>
<% provide(:title, "Wypełnianie ankiety") %>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-offset-1 col-lg-10 col-lg-offset-1">
  <div class="row">
	<h1 id="survey-title" class="text-center">
	  <%= @survey.name %> <%= @is_creator%>
	</h1>
  </div>
  <%= form_tag fill_survey_path, :id => "survey-form" do %>
	<% if @survey.is_age_required || @survey.is_sex_required || @survey.is_education_required || @survey.is_location_required %>
	  <div id="respondent-info-form" class="panel panel-default">
		<h1 class="text-center">Dane wymagane od ankietowanego:</h1>
		<% if @survey.is_age_required %>
		  <div>
			<h2>Wiek:</h2>
			<%= number_field_tag("respondent[age]", nil, in: 1...100, class: "form-control respondent-age-input") %>
		  </div>
		  <% end %>
			<% if @survey.is_sex_required %>
			  <div class="respondent-sex">
				<h2>Płeć:</h2>
				<div class="radio">
				  <h3><label><%= radio_button_tag("respondent[sex]", 'K') %>Kobieta</label></h3>
				</div>
				<div class="radio">
				  <h3><label><%= radio_button_tag("respondent[sex]", 'M') %>Mężczyzna</label></h3>
				</div>
			  </div>
			<% end %>
			<% if @survey.is_education_required %>
			  <div>
				<h2>Wykształcenie:</h2>
				<%= select("respondent", "education", ["podstawowe","gimnazjalne","zawodowe","średnie","wyższe"],{},{class: "form-control respondent-education-input"}) %>
			  </div>
			<% end %>
			<% if @survey.is_location_required %>
			  <div>
				<h2>Miejsce zamieszkania:</h2>
				<%= select("respondent", "location", ["do 5 tyś. mieszkańców","5-20 tyś. mieszkańców","20-100 tyś. mieszkańców","100-200 tyś. mieszkańców","200-500 tyś. mieszkańców","powyżej 500 tyś. mieszkańców"],{},{class: "form-control respondent-location-input"}) %>
			  </div>
			<% end %>
	  </div>
	  <% end %>
	  <div id="survey" class="panel panel-default">
		<% counter = 0 %>
		<% @survey.questions.each do |q| %>
		<div class="question">
		  <h2><%="#{counter+=1}. #{q.content}" %></h2>
		  <div class="answers">
		  <% q.answers.each do |a| %>
			<% if q.question_type == "JEDNOKROTNEGO_WYBORU" %>
			<div class="answer radio">
			  <h3><label><%= radio_button_tag "question[#{q.id}][]", a.id %><%= a.reply %></label></h3>
			</div>
			<% elsif q.question_type == "WIELOKROTNEGO_WYBORU"%>
			<div class="answer checkbox">
			  <h3><label><%= check_box_tag "question[#{q.id}][]", a.id %><%= a.reply %></label></h3>
			</div>
			<% end %>
		  <% end %>
		  </div>
		  </div>
		<% end %>
		<% if(@is_survey_author) %>
		  <%= submit_tag("Brak możliwości wysłania ankiety przez autora", disabled: true, class: "btn btn-primary btn-lg") %>
		<% else %>
		  <%= submit_tag("Wyślij", class: "btn btn-primary btn-lg") %>
		<% end %>
		</div>
  <% end %>
  </div>
</div>