config/routes.rb
Rails.application.routes.draw do
  resources :surveys, :path => 'ankieta', path_names: { new: 'nowa' }, :except => [:edit, :update] do
    member do
		get 'stats', :path => 'wyniki'
	end
  end
  devise_for :administrators, :path => 'uzytkownik', path_names: { sign_in: 'logowanie', sign_out: 'wylogowywanie', edit: 'profil' }
  get 'static_pages/help'
  post 'fill_survey' => 'surveys#fill', controller: 'surveys'
  root 'surveys#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'SurveySystem', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="nav navbar-nav">
		<li><%= link_to 'Pomoc', static_pages_help_url %></li>
      </ul>
      
		<ul class="nav navbar-nav pull-right">
        <% if administrator_signed_in? %>
              <li><%= link_to 'Nowa ankieta', new_survey_path %></li>
              <li><%= link_to 'Profil', edit_administrator_registration_path %></li>
              <li><%= link_to 'Wyloguj', destroy_administrator_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Logowanie', new_administrator_session_path %></li>
          <li><%= link_to 'Rejestracja', new_administrator_registration_path %></li>
        <% end %>
		</ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= yield(:title) %> | RubyOnRailsSurveySystem</title>
    <%= csrf_meta_tags %>
	<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
	<%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/locales/bootstrap-datepicker.pl.min.js"></script>
</head>

<body>

<%= render "layouts/header" %>
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>" role="alert">
      <button type="button" class="close">&times;</button>
      <%= value %>
    </div>
  <% end %>
  <%= yield %>
</div>
<%= render "layouts/footer" %>
</body>
</html>